<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Remotely_Manager</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Remotely_Icon.ico</ApplicationIcon>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.4" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.4" />
    <PackageReference Include="SkiaSharp" Version="2.88.8" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\Remotely_Icon.ico" />
    <AvaloniaResource Include="Assets\Remotely_Icon.png" />
  </ItemGroup>
</Project>
